var wordList = {
  "143": "I love you (popularized by Mister Rogers, the numbers reference the number of characters in the words 'I', 'Love' and 'you'.).",
  "2DAY": "Today.",
  "4EAE": "For ever and ever.",
  "AAAAFSSADDGSAFBMTRUYE67STABRBAFABDDAFBA": "I am having a stroke, please get me medical assistance.",
  "ADN": "Any day now.",
  "AFAIK": "As far as I know.",
  "AFK": "Away from keyboard.",
  "AFAIK": "As far as I know.",
  "AMA": "Ask me anything. Also see AMAA, ask me almost anything." ,
  "ATM": "At the moment.",
  "ASL": "Age/sex/location.",
  "B/C": "Because.",
  "B4": "Before.",
  "BF / GF": "Boyfriend / Girlfriend.",
  "BFD": "Big fucking deal.",
  "BFF": "Best friend forever.",
  "BFN": "Bye for now.",
  "BOL": "Be on later.",
  "BRB": "Be right back.",
  "BTW": "By the way.",
  "CU": "See you.",
  "CUL8R": "See you later.",
  "CYA": "See you.",
  "DGAF": "Don't give a fuck.",
  "DM": "Direct message.",
  "DWBH": "Don’t worry, be happy.",
  "F2F or FTF": "Face to face.",
  "FB": "Facebook.",
  "FBF": "Flashback Friday.",
  "FBO": "Facebook official.",
  "FF": "Follow Friday (Follow Friday is a recurring topic on Twitter. Each week, users post lists of people that they think others should followusing the #FF or #FollowFriday hashtag.).",
  "FFS": "For fucks sake.",
  "FML": "Fuck my life.",
  "FTFY": "Fixed that for you.",
  "FTL": "For the loss / For the lose.",
  "FTW": "For the win.",
  "FUBAR": "Fucked up beyond all recognition.",
  "FWB": "Friends with benefits.",
  "FWIW": "For what it’s worth.",
  "FYEO": "For your eyes only.",
  "FYI": "For your information.",
  "GG": "Good game.",
  "GFG": "Good fucking game. Can be used sarcastically to indicate a novice mistake. 'You let him get away, GFG noob'.",
  "GLHF": "Good luck, have fun.",
  "GR8": "Great.",
  "HAK": "Hugs and kisses.",
  "HAND": "Have a nice day.",
  "HMB": "Hit me back.",
  "HMU": "Hit me up.",
  "HT or H/T": "Hat tip or heard through (usually referencing news or an informative link).",
  "HTH": "Hope this helps / Happy to help.",
  "IANAL": "I am not a lawyer.",
  "IDC": "I don't care.",
  "IDK": "I don’t know.",
  "IIRC": "If I remember correctly.",
  "IKR": "I know, right?",
  "ILY / ILU": "I love you.",
  "IMHO": "In my honest opinion / In my humble opinion.",
  "IMO": "In my opinion.",
  "IRL": "In real life.",
  "ITT": "In this thread.",
  "IU2U": "It’s up to you.",
  "IYKWIM": "If you know what I mean.",
  "J/K": "Just kidding.",
  "J4F": "Just for fun.",
  "JIC": "Just in case.",
  "JSYK": "Just so you know.",
  "LMAO": "Laughing my ass off.",
  "LMFAO": "Laughing my fucking ass off.",
  "LMK": "Let me know.",
  "LMS": "Like my status.",
  "LOL": "Laughing out loud.",
  "MM": "Music Monday. Another recurring Twitter topic. In this case, users post a song or two that will get your week off to a better start.",
  "MRW": "My reaction when - usually followed by a meme.",
  "MSM": "Mainstream media.",
  "NAGI": "Not a good idea.",
  "NM": "Never mind.",
  "NMU": "Not much, you?",
  "NMS": "Not safe for the human mind.",
  "NP": "No problem or Now playing (as in “My MP3 stream is now playing LMFAO’s Party Rock.).",
  "NSFW": "Not safe for work. If this is attached to a link, you’re strongly advised not to check it out while in the workplace or any other venue where inappropriate content would be, well, inappropriate.",
  "NSFL": "Not safe for life. Usually a humorous disclaimer that something formerly innocent is going to be irreparably sullied if you click the link.",
  "NTS": "Note to self.",
  "OC": "Original content.",
  "OH": "Overheard.",
  "OMG": "Oh my God.",
  "OMW": "On my way.",
  "OOTD": "Outfit of the day.",
  "OP": "Original poster - generally regarded as a faggot.",
  "ORLY": "Oh, really? ( O v O )",
  "PAW": "Parents are watching.",
  "PDA": "Public display of affection.",
  "PLS or PLZ": "Please.",
  "PPL": "People.",
  "POTD": "Photo of the day.",
  "PTB": "Please text back.",
  "PTFO": "Passed the fuck out.",
  "QQ": "Crying. Rather than an abbreviation, this is an emoticon, a picture created in text. The tails of the capital Q form tears, while the circles are the eyes. Saying “QQ” aloud also can mimic the “boo hoo” of someone who’s upset. Usually used sarcastically or contemptuously.",
  "RAK": "Random act of kindness.",
  "RL": "Real life.",
  "ROFL": "Rolling on the floor laughing.",
  "ROFLMFAO": "Rolling on the floor laughing my ass off.",
  "RT": "Retweet. Similar to forwarding an email, Twitter lets you echo other people’s tweets for your own followers to read. In some cases, folks will ask for something they’ve said to be amplified by saying “Please RT” or “PLS RT.”.",
  "RUOK": "Are you okay? In Australia, #RUOK is a regularly trending topic, following a government initiative called RUOK Day, which raises awareness of mental health issues on social networking sites.",
  "SMH": "Shaking my head.",
  "SRSLY": "Seriously.",
  "SRS": "Serious. (Seriously)",
  "SSDD": "Same shit, different day.",
  "STFU": "Shut the fuck up.",
  "SWAK": "Sealed with a kiss.",
  "SWYP": "So, what’s your problem?",
  "TIA": "Thanks in advance.",
  "TBH": "To be honest.",
  "TBT": "Throwback thursday.",
  "TIL": "Today I learned.",
  "TIME": "Tears in my eyes.",
  "TL;DR": "Too long; Did not read.",
  "TMB": "Tweet me back.",
  "TMI": "Too much information.",
  "TMRW": "Tomorrow.",
  "TTYL": "Talk to you later.",
  "TX": "Thanks.",
  "TY or TU": "Thank you.",
  "VSF": "Very sad face.",
  "WB": "Welcome back.",
  "WTF": "What the fuck?",
  "WTPA": "Where the party at?",
  "WYCM": "Will you call me?",
  "YGM": "You’ve got mail (to alert your texting partner that you’ve contacted them via that stale old email thing. That’s sooo 2001!).",
  "YMMV": "Your mileage may vary.",
  "YW": "You’re welcome.",
  "WWJD": "What would Jesus do?",
  "ZOMG": "Oh my god (sarcastic)"
};

var wordGen = {
  randomKey: function(obj){
    var result;
    var count = 0;
    for (var prop in obj)
        if (Math.random() < 1/++count)
           result = prop;
    return result;
  },
  wordSet: function(){
    var primaryWord = this.randomKey(wordList);
    $('.mainWord').text(primaryWord);
    $('.wordDef').text(wordList[primaryWord]);
  }
};

$(document).ready(function(){
  wordGen.wordSet();
  $('.youthButt').on("click", function(){
    wordGen.wordSet();
  });
});
